[package]
name = "bb"
version = "0.1.0"
edition = "2024"

[dependencies]
logos = "0.15"
lalrpop-util = "0.22"
derive_more = {version = "2.0", features = ["from"]}
impl-tools = "0.11"
educe = "0.6.0"

[build-dependencies]
lalrpop = "0.22"

[dev-dependencies]
indoc = "2.0"
