[application]

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

[web.wasm_opt]
# The level wasm-opt should target. z is the smallest. 4 is the fastest.
level = "4"

[web.app]

# HTML title tag content
title = "Blooming Blocks"

[web.watcher]

index_on_404 = true

watch_path = ["src", "examples"]

# Theme override: "light", "dark", or "system"
theme = "system"

[bundle]
# Bundle identifier
identifier = "bb.app.miorin"

# Bundle publisher
publisher = "Miorin"

# Bundle icon
icon = ["icons/icon.png"]

# Bundle resources
resources = ["public/*"]

# Bundle copyright
copyright = "Copyright 2026 Miorin"

# Bundle category
category = "Utility"

# Bundle short description
short_description = "A document editor that catalyzes text-based design and implementation."

# Bundle long description
long_description = """
A document editor that catalyzes text-based design and implementation.
"""
